### ISSUE TITLE
Cannot specify baseUrl for UI

### ISSUE THREAD

**Issue by eclipsetalk** [bitnami/bitnami-docker-minio#39]
I can't find a way to specify a base url for the Web UI.
I've deployed minio on a pod. The way traffic makes its way to minio Web UI is a follow:
Citrix Load Balancer and then to a stio Ingress Gateway.
How can I specify the base url to start the UI?
Thanks

**Comment by yilmi** [comment]
Hi @eclipsetalk,

We receive a lot of support requests, and we really try our best to help out, we just ask users to follow our issues templates. Please try to follow it next time :-) 

If you're deploying minio using our charts, you should open a ticket for our charts, because I don't think the container logic is the culprit here.

Did you make any progress on this? Could you give me a bit more details? And if the issue is when using our charts, could you open an issue in our chart repo giving us the value used and some details about the environment?

Thanks,
Yass

**Comment by eclipsetalk** [comment]
I resolved the issue. It had nothing to do with the chart.
Thanks

**Comment by yilmi** [comment]
If you have a moment later to share with the community how you solved it, someone might find it helpful. Glad to hear you were able to solve it! 👍

**Comment by eclipsetalk** [comment]
My issue was with the gateway. I'm using a Citrix load balancer with istio Ingress gateway. I needed to create virtualservice for ingress traffic.
