### ISSUE TITLE
isn't this security concern if we are storing access key and secrets key like this in minio data directory.

### ISSUE THREAD

**Issue by poonam-davari** [bitnami/bitnami-docker-minio#48]
https://github.com/bitnami/bitnami-docker-minio/blob/d5bdb753346837e8ac9c3b700223151c50784747/2022/debian-10/rootfs/opt/bitnami/scripts/libminio.sh#L316
AND
https://github.com/bitnami/bitnami-docker-minio/blob/d5bdb753346837e8ac9c3b700223151c50784747/2022/debian-10/rootfs/opt/bitnami/scripts/libminio.sh#L317

isn't this security concern if we are storing access key and secrets key like this in minio data directory.
I am deploying minio as kubernetes pod and /data is actually mounted on my base OS's file system (its persistent mount)
So these files inside /data are available on my filesystem which I dont want.

I am setting **MINIO_FORCE_NEW_KEYS=no** which will always remain same.
if I remove minio_regenerate_keys function will that cause any issue?
Asking here because I cannot foresee any issues as I am not expert in minio.

Thanks & Regards,
Poonam Davari

**Comment by rafariossaa** [comment]
Hi,

> isn't this security concern if we are storing access key and secrets key like this in minio data directory.
I am deploying minio as kubernetes pod and /data is actually mounted on my base OS's file system (its persistent mount)
So these files inside /data are available on my filesystem which I dont want.

You should give the proper rights to the file system in order to make it not accessible to anyone not desired. I can not see any problems there meanwhile you give the proper rights. 

> I am setting MINIO_FORCE_NEW_KEYS=no which will always remain same.
if I remove minio_regenerate_keys function will that cause any issue?
Asking here because I cannot foresee any issues as I am not expert in minio.

I am not either an expert in minio. I am not sure why would you want to remove that function. You can set `MINIO_FORCE_NEW_KEYS=no` and that avoids to regenerate the keys, but you will need the files that store the credentials.

**Comment by poonam-davari** [comment]
I think minio_regenerate_keys should only be called when MINIO_FORCE_NEW_KEYS=yes.
I dont get why there is need of storing credentials.

**Comment by rafariossaa** [comment]
Hi,
  You need to store them to be able to change the credentials. Minio needs the old credentials in `MINIO_ROOT_xxxx_OLD` to be able to set the admin credentials to the new `MINIO_ROOT_xxxx` when `MINIO_FORCE_NEW_KEYS=yes`
