### ISSUE TITLE
Support ARM64

### ISSUE THREAD

**Issue by pan3793** [bitnami/bitnami-docker-minio#59]
### Name and Version

bitnami/minio:latest

### What is the problem this feature will solve?

Support ARM64 platform

### What is the feature you are proposing to solve the problem?

Support ARM64 platform

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.

**Comment by pan3793** [comment]
Thanks for input, is there an ETA for MinIO?

**Comment by rafariossaa** [comment]
Hi,
  I am sorry but there is not an ETA for this yet.

**Comment by pan3793** [comment]
Is there anything I can do to speed it up?

**Comment by rafariossaa** [comment]
I am sorry, but there is not. 
In any case I would suggest you to ping https://github.com/bitnami/charts/issues/7305. We are concentrating all ARM64 conversation in that issue.

**Comment by alekc** [comment]
for what it's worth (until the arm support is officially deployed by bitnami), I've put up a fork with modded dockerfile in 
https://github.com/alekc-forks/bitnami-docker-minio-multiarch (images are deployed here: https://hub.docker.com/repository/docker/alekcander/bitnami-minio-multiarch/tags?page=1&ordering=last_updated)

Keep in mind that (as it turns out), you cannot have multi arch minio cluster due to https://github.com/minio/minio/issues/12202, so it's either amd64 or arm64 for all nodes
